version: '3'
services:
  voting-system:
    container_name: voting-system
    build:
      context: .
      dockerfile: Dockerfile
    image: voting-system:latest
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"