spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      user: southsystem
      password: teste
      uri: mongodb+srv://southsystem:teste@southsystem-application.bvk8x.mongodb.net/?retryWrites=true&w=majority
      database: southsystem
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
rabbitmq:
  exchange: exchange
  queue: queue
  routingkey: routingkey

eligibility:
  url: https://user-info.herokuapp.com